name: Check links

on:
  pull_request:
    paths:
      - "docs/**"
  push:
    branches:
      - main
    paths:
      - "docs/**"
  schedule:
    - cron: "0 14 * * 1"
  workflow_dispatch:

jobs:
  check-source-links:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Check links in docs
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --max-retries 2
            --max-concurrency 8
            './docs/**/*.md'

